FROM registry.hub.docker.com/entando/entando-tomcat-base:7.3.0
ARG VERSION

### Required OpenShift Labels
LABEL name="Villanova App" \
      maintainer="dev@villanova.com" \
      vendor="Villanova Spa" \
      version="${VERSION}" \
      release="7.3.0" \
      summary="Villanova Application" \
      description="This Villanova app engine application provides APIs and composition for Villanova applications"

#COPY target/generated-resources/licenses /licenses
#COPY target/generated-resources/licenses.xml /

COPY --chown=185:0 webapp/target/*.war /usr/local/tomcat/webapps/

RUN $ENTANDO_COMMON_PATH/init-derby-from-war.sh

RUN rm -rf /tmp/*.jpg
