FROM registry.hub.docker.com/entando/entando-eap73-clustered-base:7.2.0
ARG VERSION

### Required OpenShift Labels
LABEL name="Villanova App" \
      maintainer="dev@villanova.com" \
      vendor="Villanova Spa" \
      version="${VERSION}" \
      release="0.9.0" \
      summary="Villanova Application" \
      description="This Villanova app engine application provides APIs and composition for Villanova applications"

#COPY target/generated-resources/licenses /licenses
#COPY target/generated-resources/licenses.xml /

COPY webapp/target/*.war /opt/eap/standalone/deployments/

RUN $ENTANDO_COMMON_PATH/init-derby-from-war.sh

RUN rm -rf /tmp/*.jpg
